import { useEffect, useRef, useState } from "react";
import type { EngineDescriptor } from "./protocol.js";

/**
 * Style selector that shows each hand rather than naming it: every option is
 * the pre-rendered preview ink (apps/web/public/styles/, regenerated by
 * packages/ink-graves/scripts/make_style_previews.ts and
 * packages/ink-calligrapher/scripts/make_style_previews.ts) with the style's
 * short name as secondary text. Options without a preview (e.g. the
 * calligrapher's "random") show the name alone. Combobox-with-listbox
 * pattern: the trigger keeps focus, arrows move the highlight, Enter picks,
 * Escape closes.
 */

export interface StyleOption {
  id: number | null;
  label: string;
  preview: string | null;
}

/** Each engine has its own preview set under public/styles/. */
export function styleOptions(engine: EngineDescriptor | null): StyleOption[] {
  if (!engine) return [{ id: null, label: "freehand", preview: "/styles/freehand.svg" }];
  const prefix = engine.id === "graves" ? "/styles" : `/styles/${engine.id}`;
  return [
    {
      id: null,
      label: engine.nullStyleLabel,
      preview: engine.id === "graves" ? `${prefix}/freehand.svg` : null,
    },
    ...engine.styles.map((id) => ({
      id,
      label: `style ${id}`,
      preview: `${prefix}/style-${id}.svg`,
    })),
  ];
}

interface StylePickerProps {
  options: StyleOption[];
  value: number | null;
  onChange: (id: number | null) => void;
}

export default function StylePicker({ options, value, onChange }: StylePickerProps) {
  const [open, setOpen] = useState(false);
  const [highlight, setHighlight] = useState(0);
  const rootRef = useRef<HTMLDivElement>(null);
  const listRef = useRef<HTMLUListElement>(null);

  const selectedIndex = Math.max(
    0,
    options.findIndex((option) => option.id === value),
  );
  const selected = options[selectedIndex]!;

  useEffect(() => {
    if (!open) return;
    const onPointerDown = (event: MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", onPointerDown);
    return () => document.removeEventListener("mousedown", onPointerDown);
  }, [open]);

  useEffect(() => {
    if (!open) return;
    listRef.current?.children[highlight]?.scrollIntoView({ block: "nearest" });
  }, [open, highlight]);

  function openPanel() {
    setHighlight(selectedIndex);
    setOpen(true);
  }

  function choose(index: number) {
    onChange(options[index]!.id);
    setOpen(false);
  }

  function onKeyDown(event: React.KeyboardEvent) {
    if (!open) {
      if (["ArrowDown", "ArrowUp", "Enter", " "].includes(event.key)) {
        event.preventDefault();
        openPanel();
      }
      return;
    }
    switch (event.key) {
      case "ArrowDown":
        event.preventDefault();
        setHighlight((index) => Math.min(index + 1, options.length - 1));
        break;
      case "ArrowUp":
        event.preventDefault();
        setHighlight((index) => Math.max(index - 1, 0));
        break;
      case "Home":
        event.preventDefault();
        setHighlight(0);
        break;
      case "End":
        event.preventDefault();
        setHighlight(options.length - 1);
        break;
      case "Enter":
      case " ":
        event.preventDefault();
        choose(highlight);
        break;
      case "Escape":
        event.preventDefault();
        setOpen(false);
        break;
      case "Tab":
        setOpen(false);
        break;
    }
  }

  return (
    <div className="style-picker" ref={rootRef}>
      <button
        type="button"
        className="style-picker-trigger"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label={`handwriting style: ${selected.label}`}
        onClick={() => (open ? setOpen(false) : openPanel())}
        onKeyDown={onKeyDown}
      >
        {selected.preview && <img src={selected.preview} alt="" draggable={false} />}
        <span className="style-picker-name">{selected.label}</span>
        <span className="style-picker-caret" aria-hidden>
          ▾
        </span>
      </button>
      {open && (
        <ul className="style-picker-panel" role="listbox" ref={listRef}>
          {options.map((option, index) => (
            <li
              key={option.label}
              role="option"
              aria-selected={index === selectedIndex}
              className={
                "style-picker-option" +
                (index === highlight ? " highlighted" : "") +
                (index === selectedIndex ? " selected" : "")
              }
              onMouseEnter={() => setHighlight(index)}
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => choose(index)}
            >
              {option.preview && (
                <img src={option.preview} alt="" draggable={false} loading="lazy" />
              )}
              <span className="style-picker-name">{option.label}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
