import { useEffect, useRef, useState } from "react";
import { ChevronDownIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import type { EngineDescriptor } from "./protocol.js";

/**
 * Style selector that shows each hand rather than naming it: every option is
 * the pre-rendered preview ink (apps/web/public/styles/, regenerated by
 * packages/ink-graves/scripts/make_style_previews.ts and
 * packages/ink-calligrapher/scripts/make_style_previews.ts) with the style's
 * short name as secondary text. Combobox-with-listbox pattern: the trigger
 * keeps focus, arrows move the highlight, Enter picks, Escape closes.
 */

export interface StyleOption {
  id: number | null;
  label: string;
  preview: string | null;
}

/** Each engine has its own preview set under public/styles/. */
export function styleOptions(engine: EngineDescriptor | null): StyleOption[] {
  if (!engine) return [{ id: null, label: "freehand", preview: "/styles/freehand.svg" }];
  const prefix = engine.id === "graves" ? "/styles" : `/styles/${engine.id}`;
  const nullOption: StyleOption[] =
    engine.nullStyleLabel === null
      ? []
      : [{ id: null, label: engine.nullStyleLabel, preview: `${prefix}/freehand.svg` }];
  return [
    ...nullOption,
    ...engine.styles.map((id) => ({
      id,
      label: `style ${id}`,
      preview: `${prefix}/style-${id}.svg`,
    })),
  ];
}

interface StylePickerProps {
  options: StyleOption[];
  value: number | null;
  onChange: (id: number | null) => void;
}

export default function StylePicker({ options, value, onChange }: StylePickerProps) {
  const [open, setOpen] = useState(false);
  const [highlight, setHighlight] = useState(0);
  const rootRef = useRef<HTMLDivElement>(null);
  const listRef = useRef<HTMLUListElement>(null);

  const selectedIndex = Math.max(
    0,
    options.findIndex((option) => option.id === value),
  );
  const selected = options[selectedIndex]!;

  useEffect(() => {
    if (!open) return;
    const onPointerDown = (event: MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", onPointerDown);
    return () => document.removeEventListener("mousedown", onPointerDown);
  }, [open]);

  useEffect(() => {
    if (!open) return;
    listRef.current?.children[highlight]?.scrollIntoView({ block: "nearest" });
  }, [open, highlight]);

  function openPanel() {
    setHighlight(selectedIndex);
    setOpen(true);
  }

  function choose(index: number) {
    onChange(options[index]!.id);
    setOpen(false);
  }

  function onKeyDown(event: React.KeyboardEvent) {
    if (!open) {
      if (["ArrowDown", "ArrowUp", "Enter", " "].includes(event.key)) {
        event.preventDefault();
        openPanel();
      }
      return;
    }
    switch (event.key) {
      case "ArrowDown":
        event.preventDefault();
        setHighlight((index) => Math.min(index + 1, options.length - 1));
        break;
      case "ArrowUp":
        event.preventDefault();
        setHighlight((index) => Math.max(index - 1, 0));
        break;
      case "Home":
        event.preventDefault();
        setHighlight(0);
        break;
      case "End":
        event.preventDefault();
        setHighlight(options.length - 1);
        break;
      case "Enter":
      case " ":
        event.preventDefault();
        choose(highlight);
        break;
      case "Escape":
        event.preventDefault();
        setOpen(false);
        break;
      case "Tab":
        setOpen(false);
        break;
    }
  }

  return (
    <div className="relative max-sm:w-full" ref={rootRef}>
      <button
        type="button"
        className="style-picker-trigger flex h-8 w-full items-center gap-2.5 rounded-lg border border-input bg-transparent py-1 pr-2 pl-2.5 text-sm outline-none transition-colors select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 sm:w-auto"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label={`handwriting style: ${selected.label}`}
        onClick={() => (open ? setOpen(false) : openPanel())}
        onKeyDown={onKeyDown}
      >
        {selected.preview && (
          <img
            className="h-5 w-[150px] object-contain object-left max-sm:w-auto max-sm:min-w-0 max-sm:flex-1"
            src={selected.preview}
            alt=""
            draggable={false}
          />
        )}
        <span className="text-[11px] whitespace-nowrap text-muted-foreground">
          {selected.label}
        </span>
        <ChevronDownIcon className="size-4 shrink-0 text-muted-foreground" aria-hidden />
      </button>
      {open && (
        <ul
          className="absolute bottom-[calc(100%+6px)] left-0 z-50 max-h-[42vh] w-full overflow-y-auto rounded-lg bg-popover p-1 text-popover-foreground shadow-md ring-1 ring-foreground/10 sm:w-[340px]"
          role="listbox"
          ref={listRef}
        >
          {options.map((option, index) => (
            <li
              key={option.label}
              role="option"
              aria-selected={index === selectedIndex}
              className={cn(
                "cursor-pointer rounded-md px-2.5 pt-2 pb-1.5",
                index === highlight && "bg-accent",
              )}
              onMouseEnter={() => setHighlight(index)}
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => choose(index)}
            >
              {option.preview && (
                <img
                  className="block h-[34px] w-full object-contain object-left"
                  src={option.preview}
                  alt=""
                  draggable={false}
                  loading="lazy"
                />
              )}
              <span
                className={cn(
                  "mt-0.5 block text-[11px] whitespace-nowrap text-muted-foreground max-sm:text-right",
                  index === selectedIndex && "font-semibold text-foreground",
                )}
              >
                {option.label}
              </span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
