import { useEffect, useRef, useState } from "react";
import { ChevronDownIcon } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import type { EngineDescriptor } from "./protocol.js";

/**
 * Style selector that shows each hand rather than naming it: every option is
 * the pre-rendered preview ink (apps/web/public/styles/, regenerated by
 * packages/ink-graves/scripts/make_style_previews.ts and
 * packages/ink-calligrapher/scripts/make_style_previews.ts) with the style's
 * short name as secondary text. The trigger opens a modal dialog over a
 * blurred backdrop; inside, a listbox of previews with roving focus: arrows
 * move, Enter picks, Escape closes (handled by the dialog).
 */

export interface StyleOption {
  id: number | null;
  label: string;
  preview: string | null;
}

/** Each engine has its own preview set under public/styles/. */
export function styleOptions(engine: EngineDescriptor | null): StyleOption[] {
  if (!engine) return [{ id: null, label: "freehand", preview: "/styles/freehand.png" }];
  const prefix = engine.id === "graves" ? "/styles" : `/styles/${engine.id}`;
  const nullOption: StyleOption[] =
    engine.nullStyleLabel === null
      ? []
      : [{ id: null, label: engine.nullStyleLabel, preview: `${prefix}/freehand.png` }];
  return [
    ...nullOption,
    ...engine.styles.map((id) => ({
      id,
      label: `style ${id}`,
      preview: `${prefix}/style-${id}.png`,
    })),
  ];
}

interface StylePickerProps {
  options: StyleOption[];
  value: number | null;
  onChange: (id: number | null) => void;
}

export default function StylePicker({ options, value, onChange }: StylePickerProps) {
  const [open, setOpen] = useState(false);
  const [highlight, setHighlight] = useState(0);
  const listRef = useRef<HTMLUListElement>(null);

  const selectedIndex = Math.max(
    0,
    options.findIndex((option) => option.id === value),
  );
  const selected = options[selectedIndex]!;

  // Roving focus: the highlighted option is the focused one, so the arrow
  // keys read to assistive tech exactly as they behave.
  useEffect(() => {
    if (!open) return;
    const item = listRef.current?.children[highlight] as HTMLElement | undefined;
    item?.focus();
    item?.scrollIntoView({ block: "nearest" });
  }, [open, highlight]);

  function openChange(next: boolean) {
    if (next) setHighlight(selectedIndex);
    setOpen(next);
  }

  function choose(index: number) {
    onChange(options[index]!.id);
    setOpen(false);
  }

  function onKeyDown(event: React.KeyboardEvent) {
    switch (event.key) {
      case "ArrowDown":
        event.preventDefault();
        setHighlight((index) => Math.min(index + 1, options.length - 1));
        break;
      case "ArrowUp":
        event.preventDefault();
        setHighlight((index) => Math.max(index - 1, 0));
        break;
      case "Home":
        event.preventDefault();
        setHighlight(0);
        break;
      case "End":
        event.preventDefault();
        setHighlight(options.length - 1);
        break;
      case "Enter":
      case " ":
        event.preventDefault();
        choose(highlight);
        break;
    }
  }

  return (
    <Dialog open={open} onOpenChange={openChange}>
      {/* The trigger flexes to fill whatever room its row leaves (the
          preview shrinks first), so a longer style label can't wrap the
          picker onto its own line. */}
      <DialogTrigger
        className="style-picker-trigger flex h-8 min-w-0 flex-1 cursor-pointer items-center gap-2.5 rounded-full bg-white/80 py-1 pr-2.5 pl-3 text-sm shadow-xs outline-none transition-colors select-none focus-visible:ring-2 focus-visible:ring-ring/50 dark:bg-background/40"
        aria-label={`handwriting style: ${selected.label}`}
      >
        {selected.preview && (
          <img
            className="h-5 w-auto min-w-0 flex-1 object-contain object-left dark:invert"
            src={selected.preview}
            alt=""
            draggable={false}
          />
        )}
        <span className="text-[11px] whitespace-nowrap text-muted-foreground">
          {selected.label}
        </span>
        <ChevronDownIcon className="size-4 shrink-0 text-muted-foreground" aria-hidden />
      </DialogTrigger>
      <DialogContent className="sm:max-w-lg">
        <DialogTitle>handwriting style</DialogTitle>
        <ul
          // The selection ring draws just outside each item, so the scroll
          // container needs a sliver of padding (margin-compensated) or it
          // clips the ring on the first and last items.
          className="-mx-2 -my-0.5 flex max-h-[65vh] flex-col gap-0.5 overflow-y-auto px-2 py-0.5"
          role="listbox"
          aria-label="handwriting styles"
          ref={listRef}
          onKeyDown={onKeyDown}
        >
          {options.map((option, index) => (
            <li
              key={option.label}
              role="option"
              aria-selected={index === selectedIndex}
              tabIndex={index === highlight ? 0 : -1}
              className={cn(
                "cursor-pointer rounded-md px-2.5 pt-2 pb-1.5 outline-none",
                index === highlight && "bg-accent",
                index === selectedIndex && "ring-1 ring-ring/50",
              )}
              onMouseEnter={() => setHighlight(index)}
              onClick={() => choose(index)}
            >
              {option.preview && (
                <img
                  className="block h-[38px] w-full object-contain object-left dark:invert"
                  src={option.preview}
                  alt=""
                  draggable={false}
                  loading="lazy"
                />
              )}
              <span
                className={cn(
                  "mt-0.5 block text-[11px] whitespace-nowrap text-muted-foreground",
                  index === selectedIndex && "font-semibold text-foreground",
                )}
              >
                {option.label}
              </span>
            </li>
          ))}
        </ul>
      </DialogContent>
    </Dialog>
  );
}
